spring:
  application:
    name: api-gateway

application:
  oauth2:
    # Account to access authorization server.
    # Normally provided externally.
    client-id: api-gateway
    client-secret: secret
    access-token-uri: http://localhost:8001/oauth/token

zuul:
  sensitive-headers:
    - Cookie
    - Set-Cookie
    - WWW-Authenticate

  routes:
    # Configuration of API routing.
    # Normally this would be at least provided externally or even better using a service discovery,
    # which is out of scope for this example.
    produkt:
      path: /produkt/**
      url: http://localhost:8002/
    user:
      path: /user/**
      url: http://localhost:8001/

app:
  oauth2:
    # Account to access authorization server.
    # Normally provided externally.
    client-id: api-gateway
    client-secret: secret
    access-token-uri: http://localhost:8001/oauth/token

server:
  port: 8000

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug
      security: debug
      cloud:
        netflix:
          zuul: debug
    com:
      netflix:
        zuul: debug